libros = [
    # [Autor, Título, Género, ISBN, Editorial, Año de Publicación, Serie, Nro. Páginas, Cant. Ejemplares, Disponibilidad, Ejemplares Disponibles]
    {
        "autor": "J.K. Rowling",
        "titulo": "Harry Potter y la Piedra Filosofal",
        "genero": "Fantasia",
        "isbn": 9780747532743,
        "editorial": "Bloomsbury",
        "anio_publicacion": 1997,
        "serie": "Harry Potter",
        "nro_paginas": 223,
        "cant_ejemplares": 5,
        "disponibilidad": True,
        "ejemplares_disponibles": 2,
    },
    {
        "autor": "George R.R. Martin",
        "titulo": "Juego de Tronos",
        "genero": "Fantasia",
        "isbn": 9780553573404,
        "editorial": "Bantam Books",
        "anio_publicacion": 1996,
        "serie": "Cancion de Hielo y Fuego",
        "nro_paginas": 694,
        "cant_ejemplares": 3,
        "disponibilidad": True,
        "ejemplares_disponibles": 3,
    },
    {
        "autor": "Agatha Christie",
        "titulo": "Diez Negritos",
        "genero": "Misterio",
        "isbn": 9780007136834,
        "editorial": "HarperCollins",
        "anio_publicacion": 1939,
        "serie": "Hercule Poirot",
        "nro_paginas": 264,
        "cant_ejemplares": 7,
        "disponibilidad": False,
        "ejemplares_disponibles": 0,
    },
    {
        "autor": "Gabriel Garcia Marquez",
        "titulo": "Cien Anos de Soledad",
        "genero": "Realismo Magico",
        "isbn": 9780307474728,
        "editorial": "Vintage",
        "anio_publicacion": 1967,
        "serie": "N/A",
        "nro_paginas": 417,
        "cant_ejemplares": 4,
        "disponibilidad": False,
        "ejemplares_disponibles": 0,
    },
    {
        "autor": "Dan Brown",
        "titulo": "El Codigo Da Vinci",
        "genero": "Thriller",
        "isbn": 9780307474278,
        "editorial": "Doubleday",
        "anio_publicacion": 2003,
        "serie": "Robert Langdon",
        "nro_paginas": 489,
        "cant_ejemplares": 6,
        "disponibilidad": True,
        "ejemplares_disponibles": 1,
    },
    {
        "autor": "J.R.R. Tolkien",
        "titulo": "La Comunidad del Anillo",
        "genero": "Fantasia",
        "isbn": 9780618640157,
        "editorial": "Houghton Mifflin",
        "anio_publicacion": 1954,
        "serie": "El Senor de los Anillos",
        "nro_paginas": 423,
        "cant_ejemplares": 2,
        "disponibilidad": False,
        "ejemplares_disponibles": 0,
    },
    {
        "autor": "Suzanne Collins",
        "titulo": "Los Juegos del Hambre",
        "genero": "Distopia",
        "isbn": 9780439023528,
        "editorial": "Scholastic",
        "anio_publicacion": 2008,
        "serie": "Los Juegos del Hambre",
        "nro_paginas": 374,
        "cant_ejemplares": 8,
        "disponibilidad": True,
        "ejemplares_disponibles": 7,
    },
    {
        "autor": "Stephen King",
        "titulo": "It",
        "genero": "Terror",
        "isbn": 9780450411434,
        "editorial": "Viking Press",
        "anio_publicacion": 1986,
        "serie": "N/A",
        "nro_paginas": 1138,
        "cant_ejemplares": 5,
        "disponibilidad": False,
        "ejemplares_disponibles": 0,
    },
    {
        "autor": "Isaac Asimov",
        "titulo": "Fundacion",
        "genero": "Ciencia Ficcion",
        "isbn": 9780553293357,
        "editorial": "Spectra",
        "anio_publicacion": 1951,
        "serie": "Fundacion",
        "nro_paginas": 255,
        "cant_ejemplares": 4,
        "disponibilidad": True,
        "ejemplares_disponibles": 4,
    },
    {
        "autor": "Haruki Murakami",
        "titulo": "Norwegian Wood",
        "genero": "Ficcion",
        "isbn": 9780307476463,
        "editorial": "Vintage",
        "anio_publicacion": 1987,
        "serie": "N/A",
        "nro_paginas": 298,
        "cant_ejemplares": 3,
        "disponibilidad": False,
        "ejemplares_disponibles": 0,
    },
]
